#!/bin/bash

# LocalFinance Quick Deploy Script
# One-command deployment of enhanced LocalFinance

set -e

echo "🚀 LocalFinance Quick Deploy"
echo "============================="
echo ""

# Check if enhanced file exists
if [ ! -f "/tmp/enhanced_localfinance.py" ]; then
    echo "📄 Enhanced LocalFinance file not found."
    echo "Creating enhanced version..."
    
    # Create the enhanced file (this would normally be generated by the build process)
    echo "⚠️  Enhanced file needs to be created first."
    echo "Please run the full build process or copy the enhanced file to /tmp/enhanced_localfinance.py"
    exit 1
fi

echo "✅ Enhanced LocalFinance file found"
echo ""

# Run status check first
echo "🔍 Checking current status..."
./scripts/status.sh

echo ""
echo "🤔 Would you like to deploy the enhanced UI? (y/N)"
read -r response

if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    echo ""
    echo "🚀 Starting deployment..."
    
    # Deploy with simplified approach
    echo "📤 Uploading to Jetson..."
    
    expect << 'EOF'
set timeout 30
spawn scp /tmp/enhanced_localfinance.py sagar@10.0.0.16:/tmp/
expect "password:"
send "jetson\r"
expect eof
EOF

    if [ $? -eq 0 ]; then
        echo "✅ Upload successful"
        
        echo "🔧 Deploying enhanced UI..."
        
        expect << 'EOF'
set timeout 60
spawn ssh sagar@10.0.0.16
expect "password:"
send "jetson\r"
expect "$ "

# Stop existing server
send "sudo pkill -f production_localfinance.py || echo 'No server to stop'\r"
expect {
    "password:" {
        send "jetson\r"
        expect "$ "
    }
    "$ " {}
}

send "sleep 2\r"
expect "$ "

# Deploy enhanced version
send "cd /home/sagar/localfinance\r"
expect "$ "

send "cp production_localfinance.py production_localfinance.py.backup 2>/dev/null || echo 'No backup needed'\r"
expect "$ "

send "cp /tmp/enhanced_localfinance.py production_localfinance.py\r"
expect "$ "

send "chmod +x production_localfinance.py\r"
expect "$ "

# Start enhanced server
send "nohup python3 production_localfinance.py > logs/enhanced.log 2>&1 &\r"
expect "$ "

send "sleep 4\r"
expect "$ "

send "curl -s http://localhost:8080/health | head -3\r"
expect "$ "

send "exit\r"
expect eof
EOF
        
        echo ""
        echo "🧪 Verifying deployment..."
        sleep 3
        
        # Run status check again
        ./scripts/status.sh
        
        echo ""
        echo "🎉 Quick deployment complete!"
        echo "🌐 Access your enhanced LocalFinance at: http://10.0.0.16:8080"
        
    else
        echo "❌ Upload failed"
        exit 1
    fi
    
else
    echo "👋 Deployment cancelled"
fi